allergens/config/routes.rb
Rails.application.routes.draw do
  resources :allergens
  # resources :recipe_ingredients
  resources :ingredients, only: [:index, :show]
  resources :recipes, only: [:index, :show, :new, :create]
  resources :users, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

allergens/app/models/allergen.rb
class Allergen < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

allergens/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

allergens/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
  has_many :allergens
  has_many :users, through: :allergens
end

allergens/app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
end

allergens/app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipes
  belongs_to :ingredients
end

allergens/app/models/user.rb
class User < ApplicationRecord
  has_many :allergens
  has_many :recipes
  has_many :ingredients, through: :allergens
end

allergens/app/controllers/allergens_controller.rb
class AllergensController < ApplicationController
end

allergens/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

allergens/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

end

allergens/app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
end

allergens/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end 

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    redirect_to recipe_path(@recipe)
    # redirect_to @recipe
  end

  private

  def recipe_params
    # params.require(:recipe).permit(:new)
    params.require(:recipe).permit!
  end

end

allergens/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end
end

allergens/app/helpers/allergens_helper.rb
module AllergensHelper
end

allergens/app/helpers/application_helper.rb
module ApplicationHelper
end

allergens/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

allergens/app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

allergens/app/helpers/recipes_helper.rb
module RecipesHelper
end

allergens/app/helpers/users_helper.rb
module UsersHelper
end

allergens/app/views/ingredients/index.html.erb
<h1>All the Ingredients</h1>
<ul>
<% @ingredients.each do |t| %>
<li><%= t.name %></li>
<% end %>
</ul>

allergens/app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %>'s Detail Page</h1>

allergens/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Allergens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

allergens/app/views/recipes/index.html.erb
<h1>All Recipes</h1>
<ul>
  <% @recipes.each do |recipe| %>
  <li><%= recipe.name %></li>
<% end %>
</ul>

allergens/app/views/recipes/new.html.erb
<h1>Add a New Recipe</h1>

<%= form_for @recipe do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

allergens/app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

allergens/app/views/users/show.html.erb
<h1><%= @user.name %>'s Recipes</h1>
<ul>
  <% @user.recipes.each do |t| %>
  <li><%= t.name %></li>
  <% end %>
</ul><br>
<%= form_tag user_path(@user), method:"DELETE" do %>
<%= submit_tag "Delete User" %>
<% end %>